### ISSUE TITLE
Auto-complete words not visible

### ISSUE THREAD

**Issue by rodionos** [axibase/charts-editor#22]
Auto-complete broken (on NUR)
Try typing `poin`.

![image](https://user-images.githubusercontent.com/2098022/63998083-fdd0b080-cb08-11e9-8b75-45f918244641.png)

**Comment by PolinaShneider** [comment]
Investigated the problem. It was styles conflict — nothing common with monaco. @VeselovAlex fixed it. If problem doesn't persist anymore, the issue could be closed.
